"""Add column in Company

Revision ID: 5fb110299bdf
Revises: ef7b74bcc892
Create Date: 2025-08-07 16:13:35.019414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb110299bdf'
down_revision: Union[str, Sequence[str], None] = 'ef7b74bcc892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('office_location', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'office_location', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'office_location', type_='foreignkey')
    op.drop_column('office_location', 'company_id')
    # ### end Alembic commands ###
