"""Add confidence to attendance table

Revision ID: 68e62b558d3b
Revises: 876ebe9ca721
Create Date: 2025-08-04 22:21:44.100250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68e62b558d3b'
down_revision: Union[str, Sequence[str], None] = '876ebe9ca721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('confidence', sa.Float(), nullable=True))
    op.drop_column('office_location', 'confidence')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('office_location', sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('attendance', 'confidence')
    # ### end Alembic commands ###
