"""Added confidence column to Attendance

Revision ID: 876ebe9ca721
Revises: 59d3773e863e
Create Date: 2025-08-04 20:23:59.472998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '876ebe9ca721'
down_revision: Union[str, Sequence[str], None] = '59d3773e863e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('office_location', sa.Column('confidence', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('office_location', 'confidence')
    # ### end Alembic commands ###
