"""Add start_date and end_date to Goal

Revision ID: ec15a9273ef8
Revises: 5e9294702344
Create Date: 2025-08-04 15:07:38.720435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec15a9273ef8'
down_revision: Union[str, Sequence[str], None] = '5e9294702344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('goals', sa.Column('end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'end_date')
    op.drop_column('goals', 'start_date')
    # ### end Alembic commands ###
